apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      containers:
        - name: meu-app-container
          image: <url-do-seu-registro>/<nome-da-sua-imagem>:<tag>
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: magalu-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: meu-app-service
spec:
  selector:
    app: meu-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: clusterIP
