apiVersion: v1
kind: Secret
metadata:
  name: magalu-registry-secret
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "container-registry.br-se1.magalu.cloud": {
          "username": "SEU_USERNAME",
          "password": "SEU_PASSWORD",
          "email": "SEU_EMAIL",
        }
      }
    }
type: kubernetes.io/dockerconfigjson
